services:
  container:
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: bind
        source: ${SELECTED_DIRECTORY}
        target: /workspace/mounted_directory
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=${PULSE_SERVER}
    network_mode: "host"
    privileged: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]